Repository readmeio/metrics-sdks, pull requests merged in 2024-09, with the labels that each got.

#1032 chore(python): Update type hinting on VerifyWebhook's signature
  packages/python/readme_metrics/VerifyWebhook.py
Labels: python

#1073 feat: kong plugin
  .github/MAINTAINERS.md
  packages/kong-plugin/.busted
  packages/kong-plugin/.editorconfig
  packages/kong-plugin/.gitignore
  packages/kong-plugin/.luacheckrc
  packages/kong-plugin/.luacov
  packages/kong-plugin/.pongo/pongorc
  packages/kong-plugin/Dockerfile
  packages/kong-plugin/README.md
  packages/kong-plugin/kong/plugins/readme-plugin/handler.lua
  packages/kong-plugin/kong/plugins/readme-plugin/schema.lua
  packages/kong-plugin/spec/readme-plugin/01-integration_spec.lua
Labels: enhancement

#1068 feat(php): upgrade PHP support and dependencies
  .github/workflows/php.yml
  packages/php/composer.json
  packages/php/composer.lock
  packages/php/examples/laravel/composer.json
  packages/php/examples/laravel/composer.lock
  packages/php/src/HAR/Payload.php
  packages/php/src/Metrics.php
  test/integrations/php/laravel.Dockerfile
Labels: dependencies

#1067 feat(ruby): upgrade versions & dependencies
  .github/dependabot.yml
  .github/workflows/ruby.yml
  packages/ruby/Gemfile.lock
  packages/ruby/lib/readme/http_request.rb
  packages/ruby/readme-metrics.gemspec
  packages/ruby/spec/readme/http_request_spec.rb
Labels: dependencies

#1075 feat(php): masking
  Makefile
  packages/php/src/HAR/MaskHelper.php
  packages/php/src/HAR/Payload.php
  packages/php/tests/HAR/PayloadTest.php
Labels: enhancement
